In [1]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from matplotlib import pyplot as plt
import numpy as np
import random

In [66]:
n = 10000
m = 100
func = lambda a, b: np.sqrt(a**2 + b**2)

x = np.zeros((n, 2))
y = np.zeros((n))

for i in range(n):
    x[i][0] = random.randint(0, m)
    x[i][1] = random.randint(0, m)
    y[i] = func(x[i][0], x[i][1])

In [68]:
x[:5], y[:5]

(array([[35.,  5.],
        [96., 99.],
        [88., 92.],
        [97., 68.],
        [34., 39.]]),
 array([ 35.35533906, 137.90213921, 127.3106437 , 118.46096403,
         51.73973328]))

In [71]:
model = Sequential([
    Dense(32, activation="relu", input_shape=(2,)),
    Dense(32, activation="relu"),
    Dense(1)
])
model.compile(optimizer="adam", loss="mse")

In [73]:
model.fit(x, y, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 814us/step - loss: 0.0172
Epoch 2/20
313/313 [==============================] - 0s 793us/step - loss: 0.0137
Epoch 3/20
313/313 [==============================] - 0s 814us/step - loss: 0.0152
Epoch 4/20
313/313 [==============================] - 0s 864us/step - loss: 0.0180
Epoch 5/20
313/313 [==============================] - 0s 793us/step - loss: 0.0140
Epoch 6/20
313/313 [==============================] - 0s 764us/step - loss: 0.0143
Epoch 7/20
313/313 [==============================] - 0s 843us/step - loss: 0.0162
Epoch 8/20
313/313 [==============================] - 0s 864us/step - loss: 0.0199
Epoch 9/20
313/313 [==============================] - 0s 814us/step - loss: 0.0218
Epoch 10/20
313/313 [==============================] - 0s 793us/step - loss: 0.0206
Epoch 11/20
313/313 [==============================] - 0s 814us/step - loss: 0.0238
Epoch 12/20
313/313 [==============================] - 0s 793us/step - loss: 0.0152
E

In [77]:
model.predict([[12, 5]])

array([[13.023011]], dtype=float32)